name: CI

on:
  pull_request:
  push:
    branches: [main]

env:
  PYTHON_VERSION: "3.12"
  DEPLOY_TOOL: ${{ vars.DEPLOY_TOOL || 'sam' }}

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff black pytest
      - name: Lint
        run: |
          ruff .
          black --check .
      - name: Test
        run: |
          pytest -q

  security:
    runs-on: ubuntu-latest
    needs: lint-test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install security tools
        run: |
          python -m pip install --upgrade pip
          pip install bandit
      - name: Bandit Scan
        run: bandit -r .

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [lint-test, security]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Install deployment tools
        run: |
          python -m pip install --upgrade pip
          if [ "$DEPLOY_TOOL" = "terraform" ]; then
            pip install terraform
          else
            pip install aws-sam-cli
          fi
      - name: Deploy
        env:
          DEPLOY_TOOL: ${{ env.DEPLOY_TOOL }}
        run: |
          if [ "$DEPLOY_TOOL" = "terraform" ]; then
            terraform init
            terraform apply -auto-approve
          else
            sam deploy --guided --no-confirm-changeset
          fi
      - uses: 8398a7/action-slack@v3
        if: always()
        with:
          status: ${{ job.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
